name: Code Quality

on:
  push:
  pull_request:
    branches:
      - "**"
      - "!main"

jobs:
  checks:
    name: "Checks"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Setup node"
        uses: "actions/setup-node@v3"
        with:
          node-version: 16

      - name: "Install npm dependencies"
        run: "npm ci"

      - name: "Run Prettier"
        run: "npm run format:check"

      - name: "Run ESLint"
        run: "npm run lint"

      - name: "Run Jest"
        run: "npm run test"
